### ISSUE TITLE
Unclear info at bottom of course

### ISSUE THREAD

**Issue by andrewscofield** [leerob/vim-for-react-devs#10]
Hey Lee, thanks for writing this! I got a chance to go through it today and its great, I am very much going to try to make it my new default. I have tried vim before, but never in the react context and that did help for sure to be writing code syntax I'm more familiar with. 

One thing I'd like to point out that I'm still confused about is all the way at the end of the course, under the plugins section and the Neovim > vscode section, you make mention of `<leader>` and I cannot figure out what this is. 

The other thing, I looked into installing `nvim-ts-autotag`, clicked on the github link from the bottom of the course but I have no idea how to add a plugin. I will probably google that here in a bit but would be good to have a TODO on how to install a plugin most react devs would likely use. 

If I find a good answer on what a <leader> is and how to install a plugin, maybe I will try to issue a pull request if I feel like I'm able to contribute a good enough solution.

**Comment by leerob** [comment]
Have you had a chance to read through the Neovim Kickstart? It sets you up with a configuration file, that picks your default `<leader>` command. It's space there. So, for example, space + `sg` will do your grepping of a keyword.

Hopefully the README for the plugins helps with how to add them to your configuration file, but yeah that could be an additional resource for configuring Neovim. I linked some videos at the bottom which walk through customizing your config files.

**Comment by andrewscofield** [comment]
I did run through the Neovim Kickstart, I guess I missed the leader part during the setup part. I will do some more reading up and I'll watch those videos too. Thanks again
